[project]
name = "fmm"
version = "0.1.0"
description = "Low Rank Approximation through Fast Multipole Methods"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.2.4",
    "pytest>=8.3.5",
]
